/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package talkplay;

import classes.banco;
import classes.tabela;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.plaf.ColorUIResource;
import javax.swing.plaf.OptionPaneUI;

/**
 *
 * @author Leonardo
 */
public class denuncia extends javax.swing.JFrame {
login login = new login();
banco banco = new banco();
public static String e;
public String email = login.user;
public String senha = login.senha;
    /**
     * Creates new form denuncia
     */
    public denuncia() {
        
        initComponents();
        jLabel2.setText("Bem-vindo "+login.user);
        banco.conexao();
        try{
        String consulta = "select * from admin where email = '" + this.email.toString()+ "' and senha = '"+this.senha.toString()+"' and status = 'ativo'";            
                PreparedStatement pst1 = banco.con.prepareStatement(consulta);
                 banco.rs = pst1.executeQuery(consulta); 
                 if(!banco.rs.next()){
                     JOptionPane.showMessageDialog(null,"Perfil desativado");
                     System.exit(0);
                 }
        }catch(SQLException ex){
            
        }
        setLocationRelativeTo(null);
        preenchertabela("select * from denuncias where numero > 5");
        remover.setVisible(false);
        a.setVisible(false);
    }
    public void preenchertabela(String banco1) {
        //variavel do tipo arratlist
        ArrayList dados = new ArrayList();
        //nomeando as colunas da tabela, usando vetor
        String[] colunas = new String[]{"Email denunciado", "Número"};
        //comando para buscar dados da tabela
        banco.executaSQL(banco1);
        try {
            //volta para a primeira coluna
            banco.rs.first();
            //pode fazer  com o if
            //realizando busca de dados, caso tenha algum
            //o nome é igual ao nome do campo no bd
            do {
                dados.add(new Object[]{
                    banco.rs.getString("emaildenunciado"),
                    banco.rs.getString("numero")});
            } while (banco.rs.next());
        } catch (SQLException ex) {
        }
        tabela table = new tabela(dados, colunas);
        tabela1.setModel(table);
        //preenchendo as tabelas, no caso apenas algumas preferencias
        //no caso defini apenas o tamanho e se ela poderia ser redimensionada
        tabela1.getColumnModel().getColumn(0).setPreferredWidth(120);
        tabela1.getColumnModel().getColumn(0).setResizable(false);
        tabela1.getColumnModel().getColumn(1).setPreferredWidth(120);
        tabela1.getColumnModel().getColumn(1).setResizable(false);
        tabela1.getTableHeader().setReorderingAllowed(false);
        /*opcional*/
        //a tabela não pode ser redimensioanda
        tabela1.setAutoResizeMode(tabela1.AUTO_RESIZE_OFF);
        //seleção única
        tabela1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        remover = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        a = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(667, 402));

        tabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabela1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/teste.png"))); // NOI18N

        jLabel2.setText("jLabel2");

        remover.setBackground(new java.awt.Color(255, 255, 255));
        remover.setForeground(new java.awt.Color(143, 188, 143));
        remover.setText("Remover perfil");
        remover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                removerMouseDragged(evt);
            }
        });
        remover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removerMouseExited(evt);
            }
        });
        remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(143, 188, 143));
        jButton1.setText("Voltar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        a.setBackground(new java.awt.Color(255, 255, 255));
        a.setForeground(new java.awt.Color(143, 188, 143));
        a.setText("Ver denuncias");
        a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aMouseExited(evt);
            }
        });
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 524, Short.MAX_VALUE)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(remover, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remover)
                    .addComponent(a))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabela1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela1MouseClicked
        // TODO add your handling code here:
        remover.setVisible(true);
        a.setVisible(true);
        
    }//GEN-LAST:event_tabela1MouseClicked

    private void removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerActionPerformed
        // TODO add your handling code here:
            int linha = tabela1.getSelectedRow();
        String codigo = String.valueOf(tabela1.getValueAt(linha, 0));
    try {
        PreparedStatement pst = banco.con.prepareStatement("select * from nick where email = '"+codigo.toString()+"'");
        banco.rs = pst.executeQuery();
        if(banco.rs.next()){
            String nick = banco.rs.getString("nick");
            PreparedStatement pst16 = banco.con.prepareStatement("delete from usuario where email = '"+codigo.toString()+"'");
            pst16.executeUpdate();
            PreparedStatement pst1 = banco.con.prepareStatement("delete from amigos where nickdestinatario = '"+nick.toString()+"'");
            pst1.executeUpdate();
            PreparedStatement pst2 = banco.con.prepareStatement("delete from amigos where nickremetente = '"+nick.toString()+"'");
            pst2.executeUpdate();
            PreparedStatement pst3 = banco.con.prepareStatement("update notificacao set imagemdodestinatario = 'padrao.jpg' where nickremetente = '"+nick.toString()+"'");
            pst3.executeUpdate();
            PreparedStatement pst4 = banco.con.prepareStatement("update notificacao set nickdestinatario = 'Usuario' where nickdestinatario = '"+nick.toString()+"'");
            pst4.executeUpdate();
            PreparedStatement pst5 = banco.con.prepareStatement("update notificacao set nickremetente = 'Usuario' where nickremetente = '"+nick.toString()+"'");
            pst5.executeUpdate();
            PreparedStatement pst6 = banco.con.prepareStatement("delete from onlinenomomento where nick = '"+nick.toString()+"'");
            pst6.executeUpdate();
            PreparedStatement pst7 = banco.con.prepareStatement("delete from jogandonomomento where email = '"+codigo.toString()+"'");
            pst7.executeUpdate();
            PreparedStatement pst8 = banco.con.prepareStatement("update ranking set imagem = 'padrao.jpg' where email = '"+nick.toString()+"'");
            pst8.executeUpdate();
            PreparedStatement pst9 = banco.con.prepareStatement("update ranking set email = 'Usuario' where email = '"+nick.toString()+"'");
            pst9.executeUpdate();
            PreparedStatement pst10 = banco.con.prepareStatement("update fotodeperfil set imagem = 'padrao.jpg' where email = '"+codigo.toString()+"'");
            pst10.executeUpdate();
            PreparedStatement pst20 = banco.con.prepareStatement("update fotodeperfil set email = 'usuario@talkplay.com' where email = '"+codigo.toString()+"'");
            pst20.executeUpdate();
            PreparedStatement pst11 = banco.con.prepareStatement("delete from fotos where email = '"+codigo.toString()+"'");
             pst11.executeUpdate();
            PreparedStatement pst12 = banco.con.prepareStatement("delete from denuncias where emaildenunciado = '"+codigo.toString()+"'");
            pst12.executeUpdate();
            PreparedStatement pst13 = banco.con.prepareStatement("delete from denuncia where emaildenunciado = '"+codigo.toString()+"'");
            pst13.executeUpdate();
            PreparedStatement pst15 = banco.con.prepareStatement("update nick set nick = 'Usuario' where email = '"+codigo.toString()+"'");
            pst15.executeUpdate();
            PreparedStatement pst17 = banco.con.prepareStatement("update nick set email = 'usuario@talkplay.com' where email = '"+codigo.toString()+"'");
            pst17.executeUpdate();
         JOptionPane.showMessageDialog(null,"Usuário removido");
           remover.setVisible(false);
        a.setVisible(false);
        }
 
         
         
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null,"Erro ao encontrar email");
    }

    }//GEN-LAST:event_removerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frmgerenciar f = new frmgerenciar();
        f.setTitle("Gerenciamento Talkplay");
        this.setVisible(false);
        f.setVisible(true);
        f.setResizable(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
        int linha = tabela1.getSelectedRow();
        e = String.valueOf(tabela1.getValueAt(linha, 0));
        vedenuncias f = new vedenuncias();
        f.setTitle("Todas as denúncias do "+e);
        this.setVisible(false);
        f.setVisible(true);
        f.setResizable(false);
    }//GEN-LAST:event_aActionPerformed

    private void removerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removerMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_removerMouseDragged

    private void removerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removerMouseEntered
        // TODO add your handling code here:
        remover.setBackground(ColorUIResource.decode("#8FBC8F"));
        remover.setForeground(ColorUIResource.WHITE);
    }//GEN-LAST:event_removerMouseEntered

    private void removerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removerMouseExited
        // TODO add your handling code here:
        remover.setBackground(ColorUIResource.WHITE);
        remover.setForeground(ColorUIResource.decode("#8FBC8F"));
    }//GEN-LAST:event_removerMouseExited

    private void aMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMouseEntered
        // TODO add your handling code here:
        a.setBackground(ColorUIResource.decode("#8FBC8F"));
        a.setForeground(ColorUIResource.WHITE);
    }//GEN-LAST:event_aMouseEntered

    private void aMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMouseExited
        // TODO add your handling code here:
        a.setBackground(ColorUIResource.WHITE);
        a.setForeground(ColorUIResource.decode("#8FBC8F"));
    }//GEN-LAST:event_aMouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setBackground(ColorUIResource.decode("#8FBC8F"));
        jButton1.setForeground(ColorUIResource.WHITE);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setBackground(ColorUIResource.WHITE);
        jButton1.setForeground(ColorUIResource.decode("#8FBC8F"));
    }//GEN-LAST:event_jButton1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(denuncia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(denuncia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(denuncia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(denuncia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new denuncia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton remover;
    private javax.swing.JTable tabela1;
    // End of variables declaration//GEN-END:variables
}
