/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package talkplay;

import classes.banco;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.ColorUIResource;
import static talkplay.login.user;

/**
 *
 * @author danie
 */
public class frmcadastro extends javax.swing.JFrame {
banco banco = new banco();
    /**
     * Creates new form frmcadastro
     */
    public frmcadastro() {
        initComponents();
        setLocationRelativeTo(null);
        lbl2.setEnabled(false);
        lbl3.setEnabled(false);
        lbl4.setEnabled(false);
        txtnoe.setEnabled(false);
        txtnos.setEnabled(false);
        btnc.setEnabled(false);
        jLabel2.setEnabled(false);
        txtnos2.setEnabled(false);
        banco.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbl3 = new javax.swing.JLabel();
        txtnoe = new javax.swing.JTextField();
        lbl4 = new javax.swing.JLabel();
        txtnos = new javax.swing.JPasswordField();
        lbl2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt2 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        txt3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btnc = new javax.swing.JButton();
        txt1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnos2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(667, 402));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/teste.png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(143, 188, 143));
        jButton1.setText("Cancelar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbl3.setText("Email:");

        lbl4.setText("Senha");

        lbl2.setText("Novo cadastro");

        jLabel5.setText("Seus dados");

        jLabel6.setText("E-mail");

        jLabel7.setText("Senha");

        jLabel8.setText("Código de segurança:");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(143, 188, 143));
        jButton2.setText("Validar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnc.setBackground(new java.awt.Color(255, 255, 255));
        btnc.setForeground(new java.awt.Color(143, 188, 143));
        btnc.setText("Cadastrar");
        btnc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncMouseExited(evt);
            }
        });
        btnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncActionPerformed(evt);
            }
        });

        jLabel2.setText("Confirme a senha:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel5))
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                .addComponent(txt2)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl2)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl3)
                            .addComponent(txtnoe, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(lbl4)
                            .addComponent(txtnos)))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnc, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtnos2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lbl2)
                        .addGap(14, 14, 14)
                        .addComponent(lbl3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnoe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addComponent(btnc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        login login = new login();
        login.setTitle("Logue-se no sistema");
        login.setVisible(true);
        this.setVisible(false);
        login.setResizable(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(txt1.getText().equals("") || txt2.getText().equals("") || txt3.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Preencha todos os campos");
        }else{
            try {
                String consulta = "select * from admin where email = '" + this.txt1.getText() + "' and senha = '"+this.txt2.getText()+"' and codigodeseguranca = '"+this.txt3.getText()+"' and tipo = 'adminchefe'";            
                PreparedStatement pst = banco.con.prepareStatement(consulta);
                banco.rs = pst.executeQuery(consulta);
                if (banco.rs.next()) {
                     JOptionPane.showMessageDialog(null, "Informações validadas");
                     lbl2.setEnabled(true);
                     lbl3.setEnabled(true);
                    lbl4.setEnabled(true);
                    txtnoe.setEnabled(true);
                    txtnos.setEnabled(true);
                    btnc.setEnabled(true);
                    jLabel2.setEnabled(true);
                     txtnos2.setEnabled(true);
                    jLabel5.setEnabled(false);
                    jLabel6.setEnabled(false);
                    jLabel7.setEnabled(false);
                    jLabel8.setEnabled(false);
                    txt1.setEnabled(false);
                    txt2.setEnabled(false);
                    txt3.setEnabled(false);
                    jButton2.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Informações inválidas");
                }
            } catch (SQLException ex) {
                
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncActionPerformed
        // TODO add your handling code here:
        if(txtnoe.getText().equals("") || txtnos.getText().equals("") || txtnos2.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Preencha todos os campos");
        }else{
            String senha =  new String(txtnos.getPassword());
            String senha2 =  new String(txtnos2.getPassword());
            if(senha.equals(senha2)){
                 Random gerador = new Random();
            int numero1 = gerador.nextInt(8)+1;
            int numero2 = gerador.nextInt(8)+1;
            int numero3 = gerador.nextInt(8)+1;
            int numero4 = gerador.nextInt(8)+1;
            String valor = ""+numero1+numero2+numero3+numero4;
            int valordobanco = Integer.parseInt(valor.toString());
            try {
                String consulta = "select * from admin where email = '"+this.txtnoe.getText()+"'";
                 PreparedStatement pst1 = banco.con.prepareStatement(consulta);
                 banco.rs = pst1.executeQuery(consulta);
                if (banco.rs.next()) {
                    JOptionPane.showMessageDialog(null, "Email já cadastrado");
                }else{
                PreparedStatement pst = banco.con.prepareStatement("insert into admin (id,email,senha,tipo,status,codigodeseguranca) values (null,?,?,?,?,?)");
                pst.setString(1, txtnoe.getText());
                pst.setString(2, txtnos.getText());
                pst.setString(3, "admin");
                pst.setString(4, "ativo");
                pst.setInt(5,valordobanco);
                pst.executeUpdate();
                txtnoe.setText("");
                txtnos.setText("");
                txtnos2.setText("");
                JOptionPane.showMessageDialog(null, "Admin adicionado");
                login lo = new login();
                lo.setVisible(true);
                this.setVisible(false);
                lo.setResizable(false);
                }
            } catch (SQLException ex) {
    
            }
                
            }else{
            JOptionPane.showMessageDialog(null, "Senhas não conferem"); 
            }
        }
    }//GEN-LAST:event_btncActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        jButton2.setBackground(ColorUIResource.decode("#8FBC8F"));
        jButton2.setForeground(ColorUIResource.WHITE);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
        jButton2.setBackground(ColorUIResource.WHITE);
        jButton2.setForeground(ColorUIResource.decode("#8FBC8F"));
    }//GEN-LAST:event_jButton2MouseExited

    private void btncMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncMouseEntered
        // TODO add your handling code here:
        btnc.setBackground(ColorUIResource.decode("#8FBC8F"));
        btnc.setForeground(ColorUIResource.WHITE);
    }//GEN-LAST:event_btncMouseEntered

    private void btncMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncMouseExited
        // TODO add your handling code here:
        btnc.setBackground(ColorUIResource.WHITE);
        btnc.setForeground(ColorUIResource.decode("#8FBC8F"));
    }//GEN-LAST:event_btncMouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setBackground(ColorUIResource.decode("#8FBC8F"));
        jButton1.setForeground(ColorUIResource.WHITE);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setBackground(ColorUIResource.WHITE);
        jButton1.setForeground(ColorUIResource.decode("#8FBC8F"));
    }//GEN-LAST:event_jButton1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmcadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmcadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmcadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmcadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmcadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JTextField txt1;
    private javax.swing.JPasswordField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txtnoe;
    private javax.swing.JPasswordField txtnos;
    private javax.swing.JPasswordField txtnos2;
    // End of variables declaration//GEN-END:variables
}
