/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package talkplay;

import classes.banco;
import classes.tabela;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author danie
 */
public class frmusuario extends javax.swing.JFrame {
login login = new login();
banco banco = new banco();
public static String statususer;
public static String statusadmin;
public String email = login.user;
public String senha = login.senha;
    /**
     * Creates new form frmusuario
     */
    public frmusuario() {
        initComponents();
        setLocationRelativeTo(null);
        jLabel2.setText("Bem-vindo "+login.user);
        banco.conexao();
        try{
        String consulta = "select * from admin where email = '" + this.email.toString()+ "' and senha = '"+this.senha.toString()+"' and status = 'ativo'";            
                PreparedStatement pst1 = banco.con.prepareStatement(consulta);
                 banco.rs = pst1.executeQuery(consulta); 
                 if(!banco.rs.next()){
                     JOptionPane.showMessageDialog(null,"Perfil desativado");
                     System.exit(0);
                 }
        }catch(SQLException ex){
            
        }
        jButton1.setVisible(false);
        jButton3.setVisible(false);
        preenchertabela("select * from usuario");
    }
public void preenchertabela(String banco1) {
        //variavel do tipo arratlist
        ArrayList dados = new ArrayList();
        //nomeando as colunas da tabela, usando vetor
        String[] colunas = new String[]{"Email", "Data", "Tipo", "Número de acesso"};
        //comando para buscar dados da tabela
        banco.executaSQL(banco1);
        try {
            //volta para a primeira coluna
            banco.rs.first();
            //pode fazer  com o if
            //realizando busca de dados, caso tenha algum
            //o nome é igual ao nome do campo no bd
            do {
                dados.add(new Object[]{
                    banco.rs.getString("email"),
                    banco.rs.getString("dataa"),
                    banco.rs.getString("tipo"),
                    banco.rs.getInt("numerodeacesso")});
            } while (banco.rs.next());
        } catch (SQLException ex) {
        }
        tabela table = new tabela(dados, colunas);
        tabela1.setModel(table);
        //preenchendo as tabelas, no caso apenas algumas preferencias
        //no caso defini apenas o tamanho e se ela poderia ser redimensionada
        tabela1.getColumnModel().getColumn(0).setPreferredWidth(80);
        tabela1.getColumnModel().getColumn(0).setResizable(false);
        tabela1.getColumnModel().getColumn(1).setPreferredWidth(80);
        tabela1.getColumnModel().getColumn(1).setResizable(false);
        tabela1.getColumnModel().getColumn(2).setPreferredWidth(80);
        tabela1.getColumnModel().getColumn(2).setResizable(false);
        tabela1.getColumnModel().getColumn(3).setPreferredWidth(80);
        tabela1.getColumnModel().getColumn(3).setResizable(false);
        tabela1.getTableHeader().setReorderingAllowed(false);
        /*opcional*/
        //a tabela não pode ser redimensioanda
        tabela1.setAutoResizeMode(tabela1.AUTO_RESIZE_OFF);
        //seleção única
        tabela1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(667, 402));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/teste.png"))); // NOI18N

        jLabel2.setText("jLabel2");

        tabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabela1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela1);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(143, 188, 143));
        jButton1.setText("Ativar/Desativar conta");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(143, 188, 143));
        jButton3.setText("Mais informações");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(143, 188, 143));
        jButton2.setText("Voltar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 192, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabela1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela1MouseClicked
        // TODO add your handling code here:
         jButton1.setVisible(true);
        jButton3.setVisible(true);
    }//GEN-LAST:event_tabela1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            int linha = tabela1.getSelectedRow();
            String codigo = String.valueOf(tabela1.getValueAt(linha, 0));
            
    try {
        String consulta = "select * from nick where email = '"+codigo.toString()+"'";
        PreparedStatement pst = banco.con.prepareStatement(consulta);
        banco.rs = pst.executeQuery();
        if(banco.rs.next()){
            String tipo = banco.rs.getString("statusadmin");
            String nick = banco.rs.getString("nick");
            if(tipo.equals("Sim")){
                PreparedStatement pst1 = banco.con.prepareStatement("update nick set statusadmin = 'Não' where email = '"+codigo.toString()+"'");
                PreparedStatement pst2 = banco.con.prepareStatement("update fotodeperfil set imagem = 'padrao.jpg' where email = '"+codigo.toString()+"'");
		PreparedStatement pst4 = banco.con.prepareStatement("update notificacao set imagemdodestinatario = 'padrao.jpg' where nickremetente = '"+nick.toString()+"'");
		PreparedStatement pst5 = banco.con.prepareStatement("update ranking set imagem = 'padrao.jpg' where email = '"+codigo.toString()+"'");
		PreparedStatement pst6 = banco.con.prepareStatement("update amigos set status = 'Não' where nickremetente = '"+nick.toString()+"'");
		PreparedStatement pst7 = banco.con.prepareStatement("update amigos set status = 'Não' where nickdestinatario = '"+nick.toString()+"'");
                pst1.executeUpdate();
                pst2.executeUpdate();
                pst4.executeUpdate();
                pst5.executeUpdate();
                pst6.executeUpdate();
                pst7.executeUpdate();
                JOptionPane.showMessageDialog(null, "Desativada com sucesso");
                jButton1.setVisible(false);
                jButton3.setVisible(false);
            }else{
                String consulta1 = ("select * from fotos where email = '"+codigo.toString()+"' and atual = 'Sim'");
                PreparedStatement pst10 = banco.con.prepareStatement(consulta1);
                banco.rs = pst10.executeQuery();
                if(banco.rs.next()){
                    String img = banco.rs.getString("imagem");
                    PreparedStatement pst1 = banco.con.prepareStatement("update nick set statusadmin = 'Sim' where email = '"+codigo.toString()+"'");
                    PreparedStatement pst2 = banco.con.prepareStatement("update fotodeperfil set imagem = '"+img.toString()+"' where email = '"+codigo.toString()+"'");
                    PreparedStatement pst4 = banco.con.prepareStatement("update notificacao set imagemdodestinatario = '"+img.toString()+"' where nickremetente = '"+nick.toString()+"'");
                    PreparedStatement pst5 = banco.con.prepareStatement("update ranking set imagem = '"+img.toString()+"' where email = '"+codigo.toString()+"'");
                    PreparedStatement pst6 = banco.con.prepareStatement("update amigos set status = 'Sim' where nickremetente = '"+nick.toString()+"'");
                    PreparedStatement pst7 = banco.con.prepareStatement("update amigos set status = 'Sim' where nickdestinatario = '"+nick.toString()+"'");
                    pst1.executeUpdate();
                    pst2.executeUpdate();
                    pst4.executeUpdate();
                    pst5.executeUpdate();
                    pst6.executeUpdate();
                    pst7.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Ativada com sucesso");
                    jButton1.setVisible(false);
                    jButton3.setVisible(false);
                }else{
                PreparedStatement pst1 = banco.con.prepareStatement("update nick set statusadmin = 'Sim' where email = '"+codigo.toString()+"'");
                PreparedStatement pst2 = banco.con.prepareStatement("update fotodeperfil set imagem = 'padrao.jpg' where email = '"+codigo.toString()+"'");
		PreparedStatement pst4 = banco.con.prepareStatement("update notificacao set imagemdodestinatario = 'padrao.jpg' where nickremetente = '"+nick.toString()+"'");
		PreparedStatement pst5 = banco.con.prepareStatement("update ranking set imagem = 'padrao.jpg' where email = '"+codigo.toString()+"'");
		PreparedStatement pst6 = banco.con.prepareStatement("update amigos set status = 'Sim' where nickremetente = '"+nick.toString()+"'");
		PreparedStatement pst7 = banco.con.prepareStatement("update amigos set status = 'Sim' where nickdestinatario = '"+nick.toString()+"'");
                pst1.executeUpdate();
                pst2.executeUpdate();
                pst4.executeUpdate();
                pst5.executeUpdate();
                pst6.executeUpdate();
                pst7.executeUpdate();
                JOptionPane.showMessageDialog(null, "Ativada com sucesso");
                jButton1.setVisible(false);
                jButton3.setVisible(false);
                }
            }
        }
    } catch (SQLException ex) {
        Logger.getLogger(frmusuario.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int linha = tabela1.getSelectedRow();
        String codigo = String.valueOf(tabela1.getValueAt(linha, 0));
        
               
        try{
            PreparedStatement pst1 = banco.con.prepareStatement("select * from nick where email = '"+codigo.toString()+"'");
            banco.rs = pst1.executeQuery();
            if(banco.rs.next()){
              statususer = banco.rs.getString("statususer");
              statusadmin = banco.rs.getString("statusadmin");
            }
            PreparedStatement pst = banco.con.prepareStatement("select * from usuario where email = '"+codigo.toString()+"'");
           banco.rs = pst.executeQuery();
            if(banco.rs.next()){
                
               String nome = banco.rs.getString("nome");
               String email = banco.rs.getString("email");
               String senha = banco.rs.getString("senha");
               String resposta = banco.rs.getString("resposta");
               Date daa = banco.rs.getDate("datahora");
               String dataFormatada = new SimpleDateFormat("dd/MM/yyyy").format(daa);
                JOptionPane.showMessageDialog(null,"Nome: "+nome+"\nEmail: "+email+"\nSenha: "+senha+"\nResposta de Segurança: "+resposta+"\nAtiva pelo usuário? "+statususer+"\nAtivo pelo admin? "+statusadmin+"\nData de cadastro: "+dataFormatada);             
            }
            
        }catch(SQLException ex){
                      
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        frmgerenciar m = new frmgerenciar();
        m.setTitle("Gerenciamento Talkplay");
        m.setVisible(true);
        this.setVisible(false);
        m.setResizable(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
        jButton3.setBackground(ColorUIResource.decode("#8FBC8F"));
        jButton3.setForeground(ColorUIResource.WHITE);
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        // TODO add your handling code here:
         jButton3.setBackground(ColorUIResource.WHITE);
        jButton3.setForeground(ColorUIResource.decode("#8FBC8F"));
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setBackground(ColorUIResource.decode("#8FBC8F"));
        jButton1.setForeground(ColorUIResource.WHITE);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
         jButton1.setBackground(ColorUIResource.WHITE);
        jButton1.setForeground(ColorUIResource.decode("#8FBC8F"));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        jButton2.setBackground(ColorUIResource.decode("#8FBC8F"));
        jButton2.setForeground(ColorUIResource.WHITE);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
         jButton2.setBackground(ColorUIResource.WHITE);
        jButton2.setForeground(ColorUIResource.decode("#8FBC8F"));
    }//GEN-LAST:event_jButton2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmusuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela1;
    // End of variables declaration//GEN-END:variables
}
